name: NuGet Release

on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-passing-data:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    with:
      slnfilename: Digitalroot.Valheim.Common.Json
      projfilename: Digitalroot.Valheim.Common.Json
