name: NuGet Release

on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

jobs:
  #[PREBUILD]
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

  #[BUILD]
  build:
    needs: [prebuild]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SLN_FILE_NAME: Digitalroot.Valheim.Common.Json.sln
      PROJ: Digitalroot.Valheim.Common.Json
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: '6.0.x'
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore
        run: dotnet restore $GITHUB_WORKSPACE/src/${{ env.SLN_FILE_NAME }} --nologo

      - name: Set Version
        run: echo 'Update Version Here'

      - name: Build    
        run: dotnet build $GITHUB_WORKSPACE/src/${{ env.SLN_FILE_NAME }} -c Release --no-restore --nologo

      - name: Test  
        run: dotnet test $GITHUB_WORKSPACE/src/${{ env.SLN_FILE_NAME }} -c Release --no-build -l "trx;LogFileName=test-results.trx" --nologo

      - name: Save Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          path: ${{ github.workspace }}/src/UnitTests/TestResults/test-results.trx
          name: test-results
          retention-days: 1

      - name: Pack
        run: dotnet pack $GITHUB_WORKSPACE/src/${{ env.PROJ }}/${{ env.PROJ }}.csproj -c Release --no-restore --no-build --nologo

      - name: Save Package
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/src/${{ env.PROJ }}/bin/Release/*.nupkg
          name: nuget-package
          retention-days: 1

      - name: Save Sleet Config
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/src/sleet.json
          name: sleet-config
          retention-days: 1

      - name: get-net-sdk-project-versions-action
        uses: kzrnm/get-net-sdk-project-versions-action@b7bb297b2d300fb378be2cd93a262a15bcf9d79b
        id: get-version
        with:
          proj-path: ${{ github.workspace }}/src/${{ env.PROJ }}/${{ env.PROJ }}.csproj
      - run: echo "${{steps.get-version.outputs.version}}"
      - run: echo "${{steps.get-version.outputs.version-prefix}}" 
      - run: echo "${{steps.get-version.outputs.version-suffix}}" 
      - run: echo "${{steps.get-version.outputs.package-version}}" 
      - run: echo "${{steps.get-version.outputs.assembly-version}}" 
      - run: echo "${{steps.get-version.outputs.file-version}}" 
      - run: echo "${{steps.get-version.outputs.informational-version}}" 

  #[POSTBUILD]
  postbuild:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download nuget package
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}

      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        with:
          name: NUnit Tests                              # Name of the check run which will be created
          path: ${{ github.workspace }}/test-results.trx # Path to test results
          reporter: dotnet-trx                           # Format of test results
          path-replace-backslashes: 'true'
          list-suites: 'all'
          list-tests: 'all'
          max-annotations: '50'

  #[PUSH GH]
  push-gh-nuget:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Download nuget package
        uses: actions/download-artifact@v2
        with:
          name: nuget-package

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json

      - name: Push to GH nuget repository
        run: dotnet nuget push $GITHUB_WORKSPACE/*.nupkg --skip-duplicate

  #[PUSH S3]
  push-s3-nuget:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Download nuget package
        uses: actions/download-artifact@v2

      - name: Push to S3 nuget repository
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.NUGET_S3_REPO_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.NUGET_S3_REPO_KEY_SECRET}}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          dotnet tool install -g sleet
          sleet push $GITHUB_WORKSPACE/nuget-package --skip-existing --config $GITHUB_WORKSPACE/sleet-config/sleet.json
          sleet retention prune --config $GITHUB_WORKSPACE/sleet-config/sleet.json

  #[PUBLISH]
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ false }} # disable for now
    steps:
      - name: Download nuget package
        uses: actions/download-artifact@v2
        with:
          name: nuget-package

      - name: Publish Release
        uses: softprops/action-gh-release@0465cdad11d833cabb6414f885edd2ccdfda4b96
        with:
          files: ${{ github.workspace }}/*.nupkg
          name: "Release ${{ steps.tag.outputs.tag }}"
          #body_path: ${{ github.workspace }}/.github/RELEASE_TEMPLATE.md
          generate_release_notes: true
          draft: true
          prerelease: ${{ startsWith(steps.tag.outputs.tag, '0.') }}


