name: NuGet Package
on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**'   

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      SLN_FILE_NAME: Digitalroot.Valheim.Common.Json.sln
      PROJ: Digitalroot.Valheim.Common.Json
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.1
        with:
          #dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Restore packages
        run: dotnet restore src/${{ env.SLN_FILE_NAME }} --nologo
      - name: Build    
        run: dotnet build src/${{ env.SLN_FILE_NAME }} -c Release --no-restore --nologo
      - name: Test  
        run: dotnet test src/${{ env.SLN_FILE_NAME }} -c Release --no-build --nologo
      - name: Create the package
        run: dotnet pack src/${{ env.PROJ }}/${{ env.PROJ }}.csproj -c Release --no-restore --no-build --nologo
      - name: Publish package to Digitalroot-Valheim nuget repository
        run: dotnet nuget push src/${{ env.PROJ }}/bin/Release/*.nupkg --skip-duplicate
      - name: Push nuget package to S3 storage
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.NUGET_S3_REPO_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.NUGET_S3_REPO_KEY_SECRET}}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          dotnet tool install -g sleet
          sleet push src/${{ env.PROJ }}/bin/Release --skip-existing --config $GITHUB_WORKSPACE/src/sleet.json
          sleet retention prune --config $GITHUB_WORKSPACE/src/sleet.json
